COMPOSITE = 0
CPANSWERS = [[[|
    =
    LelandStanfordmadeafortuneinaminingventurewhenhesoldhisinterestinthismine.=Lincoln
    Thefirstwaveofargonautsdidn'tstartdigginginColomauntilwhatmonthof1848.=May
    WhatwasthenameoftheFrenchchefwhocookedacatsowellthatnoonecouldtellitfromrabbit?=Antoine
    WhatwasthelastnameofoneoftheMexicanswhofellvictimtodiscriminationinSanAndreas?=Murietta
    WhatwasthelastnameofthebartenderattheAngelsHotelthattoldataletoMarkTwain?=Coon
    WhatwasthelastnameofthemanresponsibleforstartingoneofthemostfamousminesinAmerica?=Kennedy
    WhatisthelastnameofawellknownwriterthatspenttimeinAngelsCampduringthe1860's?=Twain
    WhatisthelastnameofthemanwhoestablishedalogtradingpostonthesouthforkoftheMercedRiver?=Savage
    Whatisthelastnameofanearlyfrontiersmanwhoresignedfromthearmyin1847andsettledintheSanFransiscobayarea?=Fremont
    Whatisthelastnameofthemanwhotookaworkcrewof100Indiansand50Hawaiianservantswithhimwhenhewenttofindgold?=Sutter
    Bayardwashisfirstname,givethelastnameofthiscorrespondentfortheNewYorkTribunethatwanderedtheminingcampsduring1849.=Taylor
    StatethelastnameofthemanthatgaveSacramentoitsname.=Brannan
    AwomanwhoslastnamewasGreenbecameoneoftherichestwomenintheworldasownerofCentralEureka.Whatwasherfirstname?=Hetty
    InthecityofSutterCreek,onwhatstreetisthehomeofR.C.Downs,superintendentofLelandStanford'smine,located?=Spanish
    Inthetownof"PilotHill",AlonzoBayleyheardtherailroadwascomingthroughsohebuiltoneofthese.=hotel
    ThenicknameofabanditcalledDickwasthis.=Rattlesnake
    Atthebeginningofthegoldrush,Colomahadnoneofthis.=crime
    Givethelastnameofaninvestorinhardrockminingthatreportedlymade$50,000amonthfromhismininginterest.=Hayward
    GivethelastnameofthemanwhoimportedthefirststampmillmachinerytoMariposa.=Fremont
    GivethelastnameofthepersonforwhomRedCastlewasbuiltin1859.=Williams
    ThistypeofshopassistedSutterandMarshallinascertainingwhetherthegoldtheyfoundwasreal.=apothecary
    The"GoldBugMine"islocatedinthisminingcommunity.=Placerville
    California'sfirstpubliclibrarywasestablishedinthistown.=Volcano
    ThispresentdayNationalParkwasonceanindianstronghold.=Yosemite
    Nomatterwhichroutewastakentothelandofgold,thisdiseasewasadeadlythreat.=cholera
    IfsomeoneexperiencedtheexcitementandlureoftheCaliforniagold,theyclaimedtohaveseenoneofthese.=elephant
    Placerville,andmanyothertowns,weredestroyedbythis.=fire
    Placervilleboomedfirstasaresultofthediscoveryofgold,andsecondlyafterthediscoveryofthispreciousmetal.=silver
    TheCountyJailinthistownwasmadeoflogssosmallthatamancouldcuthiswayoutinanhourortwousingonlyhisjackknife.=Jackson
    JohnSuttercontractedJamesWilsonMarshalltobuildhimoneofthese.=sawmill
    GivethefirstnameofaprominentjournalistfortheNewYorkTribune.=Horace
    GivethelastnameofamanthatmadehisfortuneinthegoldcountryworkingonwheelbarrowsandthenreturnedtoIndiana.=Studebaker
    GivethenicknamegiventothemailmannamedThompson.=Snowshoe
    BlackBartspentsometimeinoneofthese.=hoosegow
    Whatwasthereallastnameofthemanwhohidbehindtheguiseof"BlackBart".=Bolton
    StatethelastnameofthemanwhoreceivedalandgrantfromtheMexicangovernment.=Sutter
    Statethelastnameofthepresidentinofficeatthetimeofthegoldrush.=Polk
    Statethelastnameoftheminerwhoextracted$40,000outofagopherhole.=Jenkins
    StatethefirstnameofthefounderoftheminingcampwhichwouldeventuallybecomethecityofAuburn.=Claude
    WhatdoesthenameMariposameaninSpanish?=butterfly
    WhatbuildingremainsfromoldCoarsegoldandbearsthedate1852onitscornerstone?=pumphouse
    Whattypeofminingrequiresdrilling,blasting,andstamping?=quartz
    WhattypeofarchitecturewasfoundonNabobHillinNevadaCity?=Victorian
    WhatisonetypeoflizardwildlifeyoumightseeinthePanamanianjungle?=iguanas
    WhatwasthemostprominenttheaterinSacramento?=Eagle
    WhatwasJamesWilsonMarshall'soccupation?=carpenter
    WhatkindofminingreplacedtheearliersluicinginAngelsCamp?=quartz
    Whatkindof"mulefuel"soldforadollaraquart?=barley
    WhatisthelastnameoftheMexicangovernorrulingtheterritoryofCaliforniawhenSutterarrived?=Alvarado
    Whatwereanestimated12,000Californiansdoingin1852?=farming
    WhohelpedSutterbuildhisfort.=Indians
    WherewasthefireenginethatthetownofColumbiapurchasedoriginallydestinedfor?=Tahiti
    WheredidMadameEleanorDumontdie?=Bodie
    WheredidLolaMontezgowhensheleftGrassValley?=Australia
    PhillipwalkedtoCaliforniafromNewYorkandsoldmeattotheminers.Whatwashislastname?=Armour
    Onselectedafternoons,oneofthese,accompaniedbyabull,providedsomeratherdistastefulentertainment.=bear
    Onthewaytoricheswasthefirsttimemanytravelerstastedoneofthese.Theywereadvisedtoeatonlythecore.=bananas
    ThecitizensofDryDigginschangedthecitiesnametothis.=Hangtown
    OfcourseGeorgetownwasnamedafterGeorge,butwhatwasGeorge'slastname?=Phipps
    Colomaisnexttothisriver.=American
    NamethestatethatbothWilliamA.Sampson,andRobertBradshawwerefrom.=Massachusetts
    NamethemanthatwasrobbedbyaMexicannamedCarlos.Carloswaslaterhungforhiscrime.=Perkins
    NameoneoftheoldestandrichestgoldminesinCalifornia,whichisalsooneofthedeepestintheworld?=Empire
    ThisHillwasthecountyseatofCalaverasCountypriortothathonorbeinggiventoSanAndreas.=Mokelumne
    Atailingwheel68feetindiameterwasbuiltin1912totaketailingsfromthismine,anddumpitintoadambehindJackson.=Kennedy
    ThestatueofJamesWilsonMarshallwhichnowstandsinColomaismadeofwhatkindofmetal?=bronze
    SomeChineseminersplantedanumberoftreesinthecityofColumbiawhicharecalledthe"TreesofHeaven".Whatkindoftreesarethese?=ailanthus
    Thismine,locatedinAmadorCity,wasoneoftherichestinCalifornia.=Keystone
    Bytheendof1849,thissettlementhadapopulationof12,000people.=Sacramento
    ThisbuildinginColumbiawassavedbytheeffortsofthetownschildren.=schoolhouse
    HerbertHoover,whospentsometimeinNevadaCity,earnedhisdegreeatthisuniversity.=Stanford
    WhatisthefirstwordinthenameoftheoldestbuildinginMurphystoday?=Travers
    TravelerstakingtherouteacrosstheIsthmusofPanamadisembarkedatthemouthofthisriver.=Chagres
    The"ShannonKnoxHouse"istheoldestbuildinginGeorgetown.Itwasbuiltfrommaterialstransportedaround=lumber
    In1851aFrenchmannamedBanquebuiltthefirststore.(fillintheblank)=brick
    Asteadydietofsaltyprovisionssometimescausedthisdisease.=scurvy
    GeorgeLegercametoMokelumneHillin1851.Wheredidhecomefrom?=Germany
    Thesedigginscomprisedthebiggesthydraulicmineintheworld.=Malakoff
    Auburn,CaliforniawasnamedbyminersfromacityalsonamedAuburninadifferentstate.Whatstateweretheyfrom?=NewYork
    Bennagerwashisfirstname,butwhatwasthelastnameofthestorekeeperthatmadeaspectaculardiscoveryinAngelsCamp?=Raspberry
    GraniteCitylatercametobeknownasthiscity.=Folsom
    Mr.MillsownedoneofthefourbanksinColumbiaduringitsheyday.Whatwashisfirstname?=Darius
    Finishthislinefromapopulardittyinthegoldfields:"WasitThompson,orJohnsonor"=Bates
    SutterCreekisthelocationoftheonlywater-poweredoneoftheseintheUnitedStates.=foundry
    Manyminersrushedforgoldin1848.Almostalloftheseminerscamefromwhere?=California
    Atypicalminerjustmightbakesomeoftheseforbreakfast.=pancakes
]]]

script[cp]:
    code = [[[$(CRLF)
        last_question = "";

        func update()
        {
          if (!script_running(cpscript))
          {
            // Match on 'Trivia'
            match_cga = scraper_match("BFNXDUAZ7", "TYFoqe0n8Lf1BWFH483H#5z1G0qRn5JgfciMbq0GJ#M6V1z5YTslNQ", 1);
            match_ega = scraper_match("BFNXDUAZ7", "WCwx#ef24Vn1hem208UGbjz1rncjP5creZ6Mp1YY1#6FwHb5fKytld", 1);
            match_com = scraper_match("BFAXDT6Z7", "x3uOmeitAGH1helsU8DOvKX1wzwtz52JpVKMfqm#t#Bimpv59jGPZT", 1);

            if (match_ega || match_cga || match_com)
            {
              text = scraper_string("PaNHs9zKPaNKP9zMzaNMz9zPXaNPX9zR7aNR79zUfaNUf9zXDaNXD9zZmaNZm9zcKaNcK9zeuaeu9zhSaNhS9zj2aNj29zmaaNma9zo9aNo99zrhaNrh9zuF", "8x8", 0, "$$(COMPOSITE)");
              pre = substr(text, 1, 15);

              if (pre != "Heycityslicker!")
              {
                question = substr(text, 0, strstr(text, "Here'sahintforya!"));
                answer = strmap(question, "$$(CPANSWERS)");

                if (question != last_question && answer != "")
                {
                  echo("Question: " + question);
                  echo("Answer: " + answer);
                  last_question = question;

                  if (!prop("noautocp"))
                    cpscript = script_run_async("cpauto", answer+"\r");

                  if (!prop("notextcp"))
                    overlay_show("cpoverlay", 1, "The correct answer is: " + answer);
                }
              }
            }
            else
            {
              overlay_hide("cpoverlay");
            }
          }
        }

        func cpauto(value)
        {
          input_lockout(true);
          sleep(1000);
          keyboard_type(value);
          sleep(500);
          input_lockout(false);
        }
    ]]]
end
