$(include font-gr-hercules.inc)

CPANSWERS = [[[|
    =
    LelandStanfordmadeafortuneinaminingventurewhenhesoldhisinterestinthismine.=Lincoln
    Thefirstwaveofargonautsdidn'tstartdigginginColomauntilwhatmonthof1848.=May
    WhatwasthenameoftheFrenchchefwhocookedacatsowellthatnoonecouldtellitfromrabbit?=Antoine
    WhatwasthelastnameofoneoftheMexicanswhofellvictimtodiscriminationinSanAndreas?=Murietta
    WhatwasthelastnameofthebartenderattheAngelsHotelthattoldataletoMarkTwain?=Coon
    WhatwasthelastnameofthemanresponsibleforstartingoneofthemostfamousminesinAmerica?=Kennedy
    WhatisthelastnameofawellknownwriterthatspenttimeinAngelsCampduringthe1860's?=Twain
    WhatisthelastnameofthemanwhoestablishedalogtradingpostonthesouthforkoftheMercedRiver?=Savage
    Whatisthelastnameofanearlyfrontiersmanwhoresignedfromthearmyin1847andsettledintheSanFransiscobayarea?=Fremont
    Whatisthelastnameofthemanwhotookaworkcrewof100Indiansand50Hawaiianservantswithhimwhenhewenttofindgold?=Sutter
    Bayardwashisfirstname,givethelastnameofthiscorrespondentfortheNewYorkTribunethatwanderedtheminingcampsduring1849.=Taylor
    StatethelastnameofthemanthatgaveSacramentoitsname.=Brannan
    AwomanwhoslastnamewasGreenbecameoneoftherichestwomenintheworldasownerofCentralEureka.Whatwasherfirstname?=Hetty
    InthecityofSutterCreek,onwhatstreetisthehomeofR.C.Downs,superintendentofLelandStanford'smine,located?=Spanish
    Inthetownof"PilotHill",AlonzoBayleyheardtherailroadwascomingthroughsohebuiltoneofthese.=hotel
    ThenicknameofabanditcalledDickwasthis.=Rattlesnake
    Atthebeginningofthegoldrush,Colomahadnoneofthis.=crime
    Givethelastnameofaninvestorinhardrockminingthatreportedlymade$50,000amonthfromhismininginterest.=Hayward
    GivethelastnameofthemanwhoimportedthefirststampmillmachinerytoMariposa.=Fremont
    GivethelastnameofthepersonforwhomRedCastlewasbuiltin1859.=Williams
    ThistypeofshopassistedSutterandMarshallinascertainingwhetherthegoldtheyfoundwasreal.=apothecary
    The"GoldBugMine"islocatedinthisminingcommunity.=Placerville
    California'sfirstpubliclibrarywasestablishedinthistown.=Volcano
    ThispresentdayNationalParkwasonceanindianstronghold.=Yosemite
    Nomatterwhichroutewastakentothelandofgold,thisdiseasewasadeadlythreat.=cholera
    IfsomeoneexperiencedtheexcitementandlureoftheCaliforniagold,theyclaimedtohaveseenoneofthese.=elephant
    Placerville,andmanyothertowns,weredestroyedbythis.=fire
    Placervilleboomedfirstasaresultofthediscoveryofgold,andsecondlyafterthediscoveryofthispreciousmetal.=silver
    TheCountyJailinthistownwasmadeoflogssosmallthatamancouldcuthiswayoutinanhourortwousingonlyhisjackknife.=Jackson
    JohnSuttercontractedJamesWilsonMarshalltobuildhimoneofthese.=sawmill
    GivethefirstnameofaprominentjournalistfortheNewYorkTribune.=Horace
    GivethelastnameofamanthatmadehisfortuneinthegoldcountryworkingonwheelbarrowsandthenreturnedtoIndiana.=Studebaker
    GivethenicknamegiventothemailmannamedThompson.=Snowshoe
    BlackBartspentsometimeinoneofthese.=hoosegow
    Whatwasthereallastnameofthemanwhohidbehindtheguiseof"BlackBart".=Bolton
    StatethelastnameofthemanwhoreceivedalandgrantfromtheMexicangovernment.=Sutter
    Statethelastnameofthepresidentinofficeatthetimeofthegoldrush.=Polk
    Statethelastnameoftheminerwhoextracted$40,000outofagopherhole.=Jenkins
    StatethefirstnameofthefounderoftheminingcampwhichwouldeventuallybecomethecityofAuburn.=Claude
    WhatdoesthenameMariposameaninSpanish?=butterfly
    WhatbuildingremainsfromoldCoarsegoldandbearsthedate1852onitscornerstone?=pumphouse
    Whattypeofminingrequiresdrilling,blasting,andstamping?=quartz
    WhattypeofarchitecturewasfoundonNabobHillinNevadaCity?=Victorian
    WhatisonetypeoflizardwildlifeyoumightseeinthePanamanianjungle?=iguanas
    WhatwasthemostprominenttheaterinSacramento?=Eagle
    WhatwasJamesWilsonMarshall'soccupation?=carpenter
    WhatkindofminingreplacedtheearliersluicinginAngelsCamp?=quartz
    Whatkindof"mulefuel"soldforadollaraquart?=barley
    WhatisthelastnameoftheMexicangovernorrulingtheterritoryofCaliforniawhenSutterarrived?=Alvarado
    Whatwereanestimated12,000Californiansdoingin1852?=farming
    WhohelpedSutterbuildhisfort.=Indians
    WherewasthefireenginethatthetownofColumbiapurchasedoriginallydestinedfor?=Tahiti
    WheredidMadameEleanorDumontdie?=Bodie
    WheredidLolaMontezgowhensheleftGrassValley?=Australia
    PhillipwalkedtoCaliforniafromNewYorkandsoldmeattotheminers.Whatwashislastname?=Armour
    Onselectedafternoons,oneofthese,accompaniedbyabull,providedsomeratherdistastefulentertainment.=bear
    Onthewaytoricheswasthefirsttimemanytravelerstastedoneofthese.Theywereadvisedtoeatonlythecore.=bananas
    ThecitizensofDryDigginschangedthecitiesnametothis.=Hangtown
    OfcourseGeorgetownwasnamedafterGeorge,butwhatwasGeorge'slastname?=Phipps
    Colomaisnexttothisriver.=American
    NamethestatethatbothWilliamA.Sampson,andRobertBradshawwerefrom.=Massachusetts
    NamethemanthatwasrobbedbyaMexicannamedCarlos.Carloswaslaterhungforhiscrime.=Perkins
    NameoneoftheoldestandrichestgoldminesinCalifornia,whichisalsooneofthedeepestintheworld?=Empire
    ThisHillwasthecountyseatofCalaverasCountypriortothathonorbeinggiventoSanAndreas.=Mokelumne
    Atailingwheel68feetindiameterwasbuiltin1912totaketailingsfromthismine,anddumpitintoadambehindJackson.=Kennedy
    ThestatueofJamesWilsonMarshallwhichnowstandsinColomaismadeofwhatkindofmetal?=bronze
    SomeChineseminersplantedanumberoftreesinthecityofColumbiawhicharecalledthe"TreesofHeaven".Whatkindoftreesarethese?=ailanthus
    Thismine,locatedinAmadorCity,wasoneoftherichestinCalifornia.=Keystone
    Bytheendof1849,thissettlementhadapopulationof12,000people.=Sacramento
    ThisbuildinginColumbiawassavedbytheeffortsofthetownschildren.=schoolhouse
    HerbertHoover,whospentsometimeinNevadaCity,earnedhisdegreeatthisuniversity.=Stanford
    WhatisthefirstwordinthenameoftheoldestbuildinginMurphystoday?=Travers
    TravelerstakingtherouteacrosstheIsthmusofPanamadisembarkedatthemouthofthisriver.=Chagres
    The"ShannonKnoxHouse"istheoldestbuildinginGeorgetown.ItwasbuiltfrommaterialstransportedaroundCapeHorn.=lumber
    In1851aFrenchmannamedBanquebuiltthefirststore.(fillintheblank)=brick
    Asteadydietofsaltyprovisionssometimescausedthisdisease.=scurvy
    GeorgeLegercametoMokelumneHillin1851.Wheredidhecomefrom?=Germany
    Thesedigginscomprisedthebiggesthydraulicmineintheworld.=Malakoff
    Auburn,CaliforniawasnamedbyminersfromacityalsonamedAuburninadifferentstate.Whatstateweretheyfrom?=NewYork
    Bennagerwashisfirstname,butwhatwasthelastnameofthestorekeeperthatmadeaspectaculardiscoveryinAngelsCamp?=Raspberry
    GraniteCitylatercametobeknownasthiscity.=Folsom
    Mr.MillsownedoneofthefourbanksinColumbiaduringitsheyday.Whatwashisfirstname?=Darius
    Finishthislinefromapopulardittyinthegoldfields:"WasitThompson,orJohnsonor"=Bates
    SutterCreekisthelocationoftheonlywater-poweredoneoftheseintheUnitedStates.=foundry
    Manyminersrushedforgoldin1848.Almostalloftheseminerscamefromwhere?=California
    Atypicalminerjustmightbakesomeoftheseforbreakfast.=pancakes
]]]

FINGERPRINTS = [[[,
    w@tSaeT4LTz1B6LPE8KaPyb1oTbGP5FNBeGMCsud9#RcPd@56GtFBS // Composite CGA
    TYFoqe0n8Lf1BWFH483H#5z1G0qRn5JgfciMbq0GJ#M6V1z5YTslNQ // CGA
    WCwx#ef24Vn1hem208UGbjz1rncjP5creZ6Mp1YY1#6FwHb5fKytld // EGA, VGA, Tandy
]]]

script[cp]:
    code = [[[$(CRLF)
        func update()
        {
          if (!script_running(cpscript))
          {
            // Match on 'Trivia'
            match = scraper_match("BFNXDUAZ7", "$$(FINGERPRINTS)", 1);
            match_hgc = scraper_match("BILYSVVar", "FfTF#eaoEej1EjBx48Pi0t@13KAWv5tQQ5mM28v3h#aEEHv5G5G81S", 1);

            if (match || match_hgc)
            {
              if (is_hercules())
                text = scraper_string("RAAI1@@LCAALC@@NPAANP@@PdAAPd@@RqAARq@@T3AAT3@@WEAAWE@@YSAAYS@@afAAaf@@csAAcs@@e5AAe5@@hHAAhH@@jUAAjU@@lhAAlh@@nuAAnu@@p8AAp8@@sJAAsJ@@uW", "hercules", 0);
              else
                text = scraper_string("QAAHs@@KPAAKP@@MzAAMz@@PXAAPX@@R7AAR7@@UfAAUf@@XDAAXD@@ZmAAZm@@cKAAcK@@euAAeu@@hSAAhS@@j2AAj2@@maAAma@@o9AAo9@@rhAArh@@uFAAuF@@wp", "8x8[21-7A]", 0, is_composite() ? SF_HALFWIDTH : 0);

              pre = substr(text, 1, 15);

              if (pre != "Heycityslicker!")
              {
                question = substr(text, 0, strstr(text, "Here'sahintforya!"));
                answer = strmap(question, "$$(CPANSWERS)");

                if (answer != "")
                {
                  echo("Question: " + question);
                  echo("Answer: " + answer);

                  if (!prop("noautocp"))
                    cpscript = script_run_async("cpauto", answer+"\r");

                  if (!prop("notextcp"))
                    overlay_show("cpoverlay", 1, "The correct answer is: " + answer);
                }
              }
            }
            else
            {
              overlay_hide("cpoverlay");
            }
          }
        }

        func cpauto(value)
        {
          input_lockout(true);
          sleep(1000);
          keyboard_type(value);
          sleep(500);
          input_lockout(false);
        }
    ]]]
end