$(include font-8x8.inc)
$(include font-hercules.inc)

CPANSWERS = [[[|
    =
    Onpage2,whatisthefourthwordofthefirstsentence?=legend
    Onpage2,whatisthefourthwordofthesecondparagraph?=kingdom
    Onpage2,whatisthesixthwordinthesecondparagraph?=Daventry
    Onpage2,whatistheeighthwordinthesecondparagraph?=lived
    Onpage3,whatisthefourthwordinthefirstparagraph?=bravest
    Onpage3,whatisthesixthwordinthefirstparagraph?=most
    Onpage3,whatisthetenthwordinthefirstparagraph?=knights
    Onpage3,whatisthethirdwordinthesecondparagraph?=return
    Onpage3,whatisthefourthwordinthethirdparagraph?=ventured
    Onpage3,whatistheseventhwordinthethirdparagraph?=humankind
    Onpage3,whatistheeighthwordinthethirdparagraph?=dared
    Onpage3,whatisthelastwordofthethirdparagraph?=Crown
    Onpage4,whatisthethirdwordinthefirstparagraph?=ruled
    Onpage4,whatisthesixthwordofthefirstparagraph?=land
    Onpage4,whatistheseventhwordinthefirstparagraph?=with
    Onpage4,whatisthesecondwordinthesecondparagraph?=would
    Onpage4,whatisthethirdwordinthethirdparagraph?=mist
    Onpage4,whatisthefourthwordinthethirdparagraph?=cleared
    Onpage4,whatistheeighthwordinthethirdparagraph?=image
    Onpage4,whatisthelastwordinthethirdparagraph?=velvet
    Onpage5,whatisthethirdwordinthesecondparagraph?=heart
    Onpage5,whatisthefourthwordinthefirstparagraph?=tears
    Onpage5,whatisthefifthwordinthesecondparagraph?=suddenly
    Onpage5,whatisthesecondwordinthethirdparagraph?=Mirror
    Onpage5,whatistheeighthwordinthethirdparagraph?=vowed
    Onpage5,whatistheeighthwordinthefourthparagraph?=voice
    Onpage5,whatistheseventhwordinthefifthparagraph?=Graham
    Onpage5,whatistheninthwordinthefifthparagraph?=indeed
    Onpage6,whatisthethirdwordinthefirstparagraph?=married
    Onpage6,whatisthefifthwordinthefirstparagraph?=beautiful
    Onpage6,whatistheninthwordinthefirstparagraph?=rescued
    Onpage6,whatisthefourthwordinthesecondparagraph?=within
    Onpage6,whatisthesixthwordinthesecondparagraph?=forests
    Onpage6,whatistheeighthwordinthesecondparagraph?=rumblings
    Onpage6,whatisthelastwordinthesecondparagraph?=terror
    Onpage7,whatisthefirstwordinthefirstparagraph?=Meanwhile
    Onpage7,whatisthetenthwordinthefirstparagraph?=wizard
    Onpage7,whatisthethirdwordinthesecondparagraph?=solitude
    Onpage7,whatisthefifthwordinthesecondparagraph?=powerful
    Onpage7,whatisthesecondwordinthethirdparagraph?=would
    Onpage7,whatistheninthwordofthethirdparagraph?=fear
    Onpage8,whatisthefirstwordofthefirstparagraph?=Time
    Onpage8,whatisthefifthwordinthefirstparagraph?=changes
    Onpage8,whatisthelastwordofthefirstsentenceinthefirstparagraph?=sorrow // sadly never matches
    Onpage8,whatisthesecondwordinthethirdparagraph?=entire
    Onpage8,whatisthesixthwordinthethirdparagraph?=rescue
    Onpage8,whatistheninthwordinthethirdparagraph?=downfall
    Onpage9,whatisthethirdwordinthefirstparagraph?=legend
    Onpage9,whatisthefourthwordinthefirstparagraph?=shortly
    Onpage9,whatistheseventhwordinthefirstparagraph?=rescue
    Onpage9,whatistheseventhwordinthesecondparagraph?=noblest
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthefirstwordoftip#1(HOWTOMOVEAROUND)?=Basic
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthesixthwordoftip#1(HOWTOMOVEAROUND)?=interact
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthelastwordoftip#1(HOWTOMOVEAROUND)?=manual
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthefifthwordinthefirstparagraphoftip#2(STAYOUTOFDANGER)?=nature
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatistheeighthwordinthefirstparagraphoftip#2(STAYOUTOFDANGER)?=adventure
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthefourthwordinthesecondparagraphoftip#2(STAYOUTOFDANGER)?=encounter
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatistheeighthwordinthesecondparagraphoftip#2(STAYOUTOFDANGER)?=character
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthefirstwordoftip#3(BEOBSERVANT)?=Look
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthefourthwordoftip#3(BEOBSERVANT)?=examine
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthelastwordoftip#3(BEOBSERVANT)?=clues
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthefirstwordoftip#4(MAPYOURPROGRESS)?=Draw
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthefifthwordoftip#4(MAPYOURPROGRESS)?=includes
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatistheseventhwordoftip#4(MAPYOURPROGRESS)?=place
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatistheninthwordoftip#4(MAPYOURPROGRESS)?=visit
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthefourthwordoftip#5(BRINGALONGSOMEHELP)?=Tamir
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatistheseventhwordoftip#5(BRINGALONGSOMEHELP)?=terrifying
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatistheninthwordoftip#5(BRINGALONGSOMEHELP)?=night
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthelastwordoftip#5(BRINGALONGSOMEHELP)?=teams
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthelastwordoftip#7(LEAVENOSTONEUNTURNED)?=function
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthefourthwordinthefirstparagraphoftip#8(ATTHEENDOFYOURROPE)?=every
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthesixthwordinthefirstparagraphoftip#8(ATTHEENDOFYOURROPE)?=trick
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthethirdwordinthesecondparagraphoftip#8(ATTHEENDOFYOURROPE)?=reason
    InthesectionTIPSFORNEWADVENTUREPLAYERS,whatisthelastwordinthefirstparagraphoftip#8(ATTHEENDOFYOURROPE)?=spell
    WhatisthesecondwordofthefirstparagraphintheOVERVIEW?=Sierra
    WhatisthesixthwordofthefirstparagraphintheOVERVIEW?=simply
    WhatisthefirstwordofthesecondparagraphintheOVERVIEW?=Each
    WhatisthethirdwordofthesecondparagraphintheOVERVIEW?=Animated
    Whatisthelastwordstartingwith'b'intheverblist?=Bridle
]]]

script[cp]:
    code = [[[$(CRLF)
        mode = prop("composite") ? prop("composite") : prop("videohw");
        mode = prop("machine") == "tandy" ? prop("machine") : mode;

        cpactive = "";

        func update()
        {
          if (!script_running(cpscript))
          {
            if (mode == "hercules")
              str = scraper_string("BAAPR@@R2", "herc", 0);
            else if (mode == "oldcga")
              str = scraper_string("BIAPX2AR7", "8x8", 0, SF_HALFWIDTH);
            else
              str = scraper_string("BIAPX2AR7", "8x8", 0);

            if (str == "Inordertoverifyyourlegal")
            {
              if (mode == "hercules")
                question = scraper_string("FAAeu@@hSAAhS@@j3AAj3@@mcAAmc@@pBAApB@@rm", "herc", 0);
              else // Every other mode with a check on composite
                question = scraper_string("IAAeu@@hSAAhS@@j2AAj2@@maAAma@@o9AAo9@@rhAArh@@uFAAuF@@wpAAwp@@zN", "8x8", 0, mode == "oldcga" ? SF_HALFWIDTH : 0);
echo(question);

              answer = strmap(question, "$$(CPANSWERS)");

              if (answer != "" && cpactive == "")
              {
                cpactive = answer;

                echo("Question: " + question);
                echo("Answer: " + answer);

                if (!prop("noautocp"))
                  cpscript = script_run_async("cpauto", answer+"\r");

                if (!prop("notextcp"))
                  overlay_show("cpoverlay", 1, "The correct answer is: " + answer);
              }
            }
            else
            {
              cpactive = "";
              overlay_hide("cpoverlay");
            }
          }
        }

        func cpauto(value)
        {
          input_lockout(true);
          sleep(1000);
          keyboard_type(value);
          sleep(500);
          input_lockout(false);
        }
    ]]]
end