CPANSWERS = [[[|
    =
    WhichEgyptiangodwastheGreatCacklerwholaidtheCosmicEgg?=Amon Ra
    WhichEgyptiangodinventedmummification?=Anubis
    WhowastheEgyptiangoddessoflove?=Hathor
    WhichEgyptiangoddesswasthemistressofmerriment?=Hathor
    WhichEgyptiangoddesswasoneoftheoldestknowngoddessesofEgypt?=Hathor
    WhichEgyptiangodwasthespiritoflight?=Horus
    WhowasthemostpopularEgyptiangoddess?=Isis
    WhichEgyptiangoddesswasconsideredthe"Queenofallgods"?=Isis
    WhowastheEgyptiangodoffertility?=Min
    WhichEgyptiangodwasthebringerofrain?=Min
    WhowastheEgyptiangodofroadsandtravelers?=Min
    WhichEgyptiangoddessrepresenteddarkness,decay,anddeath?=Nephthys
    WhichEgyptiangodmadecropsgrow?=Osiris
    WhichEgyptiangodbuiltthecities?=Ptah
    WhichEgyptiangodprotectedartists?=Ptah
    WhichEgyptiangodwasthepatronofcraftsmen?=Ptah
    WhichEgyptiangodsymbolizedevil?=Seth
    WhichEgyptiangodrepresenteddarkness?=Seth
    WhichEgyptiangodwastheLordofUpperEgypt?=Seth
    WhichEgyptiangodwasworshippedinCrocodilopolis?=Sobek
    WhichEgyptiangodwasworshippedincitiesthatdependedonwater?=Sobek
    WhowastheEgyptiangodofwisdom?=Thoth
    WhichEgyptiangodcreatedhieroglyphics?=Thoth
    WhichEgyptiangodwrotethe"BookoftheDead"?=Thoth
    WhichEgyptiangodwasthepatronoftheartsandsciences?=Thoth
]]]

MOUSECOORDS = [[[|
    =
    0=40 90
    1=90 90
    2=140 90
    3=190 90
    4=240 90
    5=290 90
    6=40 150
    7=90 150
    8=140 150
    9=190 150
    10=240 150
    11=290 150
]]]

GODS = [[[|
    =
     Amon Ra=WxT4pZLq3#U0BGYtXxr5u7qpU8#lA#qc68QfvGVrhjnAcCs#JQ19eU=,NJqFKZzz69H5h87swwzRcCT1cwxMn1wizEaKjeZat6AZsar19Bix9f=
      Anubis=7raylfsLZY44WSre3vEd#xEynnB36Qo0WU9ZMfGAC5E41a8#p@gnWU=,oIAjuaEEgBn5VrMMgwLIFDLyuampT9PFmUSAefDD15gsCor1bc8L9f=
      Hathor=#tVCZfkWMJkVL#hOXvXVF0c0#bE3epfG5TtBuNNkarCtLQGojMrQqG=,2UYWmaVVYTL5zRx8kwyugOLxOxjf3x#fXPmAIlwrl5hPv8Px2sMWJf=
       Horus=D2Ey#Dhan1tmM0EjKP3E09AyDZnm#i9iEc9egys8ar9sVj5NldWhCU=,m0YbuaJxsGbzcayBIwAqJuHyx1m6P@yuic2A09MeB5DKE5r1DrwUlf=
        Isis=tZMlhfBhRMmAdzVW@vwyVEI0#E5kePuIApNNfL8m3KBBisaapwi46S=,wm3viaqwSIzxppw0kwAE037xHwyGv9eFwsKA0cRn15AGONL@Xas89f=
         Min=uVAr#Dz1fmFYQa5DFnoJ5Z3o#GWhqHkV10hBTRJ0fTorEu2lszszKU=,SWOyaaFtO7L5tA#cE6HoxDrxwOSoz9JQLLyAhQrFZ6SaL93@SGhnxf=
    Nephthys=puoreDWTyZ9YWu5#chWCRP5zP@10SXPScXsf7DfqKr5ItKGSC9JTWU=,2fs0Ga#JxSH5bZo8AwhHpNX9lw6kP9CrfbuK2P@V55N@Ak3x4XcmZf=
      Osiris=L4AS9ZrEFXOcs3ECD7s4@HgyB9Kd4ytMEZtBmsl6u@v9fpgsp7#FWU=,Qt02KZKS#BrxVSKYQwQYdxjyI6cG310RDXiApI9xl6ARrUT1N7Y19f=
        Ptah=UPtu7IPHvDbo#Rp73xgnA15ByfUzp5hvGUnshmyqxjJ4NiY#q92jCU=,6bWp2eFBCHn5KamnQwxTy5by@QPqv9exHr#EKdvIl6Av5#P1MXsjVf=
        Seth=lJFoFTka5JCuwSFdJoNDihaclKJB6i8Z80r3eLvgG545b484ESmjWG=,bXFt#SOjsOHzbLEXQ4nFPzP96CCvf@zqE3KI7exVN5tqwjX16MZ@pf=
       Sobek=nt6hVfBQa2GcZzhdDvbRLbUg6xM0OdGOcmFL6Uq2K5xb@mTkln3PuH=,otpMqaaiD2PxjGHakweMAQzyILAC@xhi@9aAH5ae55dYkKP1oWrZBf=
       Thoth=P9BEhf4UUt2R3bNgHva5uzU06LdDbkU7MUZZvZG5DKN5A86l8ZA9aG=,Kxyg#a90MWr9drmDkww9tN3x#N2nv1k61BOAguX8V5dCUqj@tILqpf=
]]]

HINTS = [[[|
    =
     Amon Ra=Amon Ra !!amonra.png@400!!
      Anubis=Anubis !!anubis.png@400!!
      Hathor=Hathor !!hathor.png@400!!
       Horus=Horus !!horus.png@400!!
        Isis=Isis !!isis.png@400!!
         Min=Min !!min.png@400!!
    Nephthys=Nephthys !!nephthys.png@400!!
      Osiris=Osiris !!osiris.png@400!!
        Ptah=Ptah !!ptah.png@400!!
        Seth=Seth !!seth.png@400!!
       Sobek=Sobek !!sobek.png@400!!
       Thoth=Thoth !!thoth.png@400!!
]]]

charset[vga]:
    height = 9
    char["]: bits = 600`000`600
    char[,]: bits = 010`060
    char[?]: bits = 200`400`4a0`500`200
    char[B]: bits = 420`7e0`4a0`4a0`5a0`240
    char[C]: bits = 3c0`420`420`420`440`280
    char[D]: bits = 420`7e0`420`420`440`480`300
    char[E]: bits = 520`7e0`520`520`420`420`240
    char[G]: bits = 3c0`420`420`420`4a0`2c0`080
    char[L]: bits = 420`7e0`420`020`020`040
    char[Q]: bits = 3c0`420`420`420`440`4a0`320
    char[U]: bits = 400`7c0`420`020`020`040`480`700`400
    char[W]: bits = 400`7e0`420`040`480`7e0`420`040`480`700`400
    char[a]: bits = 040`2a0`2a0`2c0`1e0`020
    char[b]: bits = 420`3e0`120`120`140`080
    char[c]: bits = 1c0`220`220`140
    char[d]: bits = 0c0`120`120`540`7c0`020
    char[e]: bits = 1c0`2a0`2a0`2a0`120`040
    char[f]: bits = 120`3e0`520`400
    char[g]: bits = 190`250`250`3a0`3c0
    char[h]: bits = 420`7e0`040`080`120`1e0`020
    char[i]: bits = 120`5e0`020
    char[k]: bits = 420`7e0`100`280`260
    char[l]: bits = 420`7e0`020
    char[m]: bits = 220`1e0`0a0`100`220`1e0`0a0`100`220`1e0`020
    char[n]: bits = 220`1e0`0a0`100`220`1e0`020
    char[o]: bits = 1c0`220`220`240`180
    char[p]: bits = 410`3f0`150`240`280`300
    char[r]: bits = 220`3e0`120`200`200
    char[s]: bits = 120`2a0`2a0`2a0`240
    char[t]: bits = 100`7c0`120
    char[u]: bits = 200`3e0`020`040`280`3e0`020
    char[v]: bits = 220`3e0`020`040`280`300`200
    char[w]: bits = 200`3e0`040`280`3e0`040`280`300
    char[y]: bits = 200`380`050`050`290`3e0
    char[z]: bits = 320`260`2a0`320`260
end

charset[ega]:
    height = 9
    char["]: bits = 600`000`000`000`600
    char[,]: bits = 010`000`060
    char[?]: bits = 200`000`400`000`4a0`000`500`000`200
    char[B]: bits = 420`000`7e0`000`4a0`000`4a0`000`5a0`000`240
    char[C]: bits = 3c0`000`420`000`420`000`420`000`440`000`280
    char[D]: bits = 420`000`7e0`000`420`000`420`000`440`000`480`000`300
    char[E]: bits = 520`000`7e0`000`520`000`520`000`420`000`420`000`240
    char[G]: bits = 3c0`000`420`000`420`000`420`000`4a0`000`2c0`000`080
    char[L]: bits = 420`000`7e0`000`420`000`020`000`020`000`040
    char[Q]: bits = 3c0`000`420`000`420`000`420`000`440`000`4a0`000`320
    char[U]: bits = 400`000`7c0`000`420`000`020`000`020`000`040`000`480`000`700`000`400
    char[W]: bits = 400`000`7e0`000`420`000`040`000`480`000`7e0`000`420`000`040`000`480`000`700`000`400
    char[a]: bits = 040`000`2a0`000`2a0`000`2c0`000`1e0`000`020
    char[b]: bits = 420`000`3e0`000`120`000`120`000`140`000`080
    char[c]: bits = 1c0`000`220`000`220`000`140
    char[d]: bits = 0c0`000`120
    char[e]: bits = 2a0`000`120`000`040
    char[f]: bits = 120`000`3e0`000`520`000`400
    char[g]: bits = 190`000`250`000`250`000`3a0`000`3c0
    char[h]: bits = 420`000`7e0`000`040`000`080
    char[i]: bits = 120`000`5e0
    char[k]: bits = 420`000`7e0`000`100`000`280`000`260
    char[l]: bits = 420`000`7e0`000`020
    char[m]: bits = 220`000`1e0`000`0a0`000`100`000`220`000`1e0`000`0a0`000`100`000`220`000`1e0`000`020
    char[n]: bits = 1e0`000`0a0`000`100`000`220`000`1e0`000`020
    char[o]: bits = 1c0`000`220`000`220`000`240
    char[p]: bits = 410`000`3f0`000`150`000`240
    char[r]: bits = 220`000`3e0
    char[s]: bits = 120`000`2a0`000`2a0`000`2a0`000`240
    char[t]: bits = 100`000`7c0`000`120
    char[u]: bits = 200`000`3e0`000`020`000`040`000`280`000`3e0`000`020
    char[v]: bits = 220`000`3e0`000`020`000`040`000`280`000`300`000`200
    char[w]: bits = 200`000`3e0`000`040`000`280`000`3e0`000`040
    char[y]: bits = 200`000`380`000`050`000`050`000`290`000`3e0
    char[z]: bits = 320`000`260`000`2a0`000`320`000`260
end

script[cp]:
    code = [[[$(CRLF)
        cpactive = "";
        regions = ["BDaR7Mzma", "BNAR7Wama", "BWmR7gAma", "BgNR7pmma", "BpzR7zNma", "BzaR78zma", "BDamuMz7N", "BNAmuWa7N", "BWmmugA7N", "BgNmupm7N", "BpzmuzN7N", "Bzamu8z7N"];

        func update()
        {
          if (!script_running(cpscript))
          {
            question = scraper_string("CAAIA@@K4AAK4@@Nx", prop("videohw"), [0xF,0x17]);
            answer = strmap(question, "$$(CPANSWERS)");
            god = strmap(answer, "$$(GODS)");

            if (answer != "")
            {
              for (region = 0; region < 12; region++)
              {
                match = scraper_match(regions[region], god, MF_MOUSE);

                if (match)
                {
                  coords = strmap(region, "$$(MOUSECOORDS)");
                  break;
                }
              }

              if (answer != cpactive)
              {
                cpactive = answer;
                echo("Question: " + question);
                echo("Answer: " + answer);

                if (!prop("noautocp"))
                  cpscript = script_run_async("cpauto", coords);

                if (!prop("notextcp"))
                  overlay_show("cpoverlay", -1, strmap(answer, "$$(HINTS)"));
              }
            }
            else
            {
              cpactive = "";
              overlay_hide("cpoverlay");
            }
          }
        }

        func cpauto(coords)
        {
          mouse_force_relative_zero(true);
          input_lockout(true);
          sleep(2000);
          x = strword(0, coords);
          y = strword(1, coords);
          echo("Moving mouse to X: " + 2*x + "   Y: " + y);
          mouse_move_abs(2*x, y);
          sleep(1000);
          mouse_click(0);
          sleep(500);
          input_lockout(false);
          mouse_force_relative_zero(false);
        }
    ]]]
end
