COMPOSITE = 0
CPANSWERS = [[[|
    =
    JohnnyCarsonis=c
    VCRstandsfor=d
    TheEastCoastis=a
    Isthissoftwarepirated?=c
    PiaZadorais=a
    Theworldis=b
    "LetItBe"wasrecordedby=d
    Allpoliticiansare=d
    Lingerieis=a
    Paul,John,Ringoand=b
    Dogirlsreallyhavecooties?=b
    WhichsongwasnotrecordedbyElvis?=c
    Edselisa=c
    Sexis=a
    RichardNixonwasthePresidentoftheUnitedStates.=c
    Duringthe70's,CarrollO'Connorportrayeda=b
    Thesong"AmericanPie"wasabout=c
    ThomasEagletonwasdroppedfromthe1972DemocraticNationalTicketwhenknowledgeofhisprevioustreatmentsbecame=c
    The70'spracticeofrunningaroundnakedwascalled=b
    PeterBenchley'snovel"Jaws"wasabout=d
    WhowasnotVice-PresidentoftheUnitedStatesin1973-74?=c
    The"ChicagoSeven"was=d
    PresidentFordprescribedfordealingwitheconomicproblems.=c
    Thetackiestseventiesfashionwas=a
    O.J.Simpsonis=d
    AngelaDavisis=b
    Detenteis=d
    Kwi-Chang-Cainebecamefamousbysaying=d
    TedKennedyisbestrememberedforhis=a
    "NORML"is=c
    TomHaydenis=d
    SpiroAgnewis=c
    Thegermthattransmitssyphilisis=b
    Kookie'saddresswas=a
    "Whoknowswhatevillurksintheheartsofmen?"=b
    AlLoweis:=c
    FrankSinatraisa=c
    RalphBoyseninvented=a
    Thefirstmanonthemoonwas=c
    "GoneWithTheWind"isabout=c
    Whoisnotasportscaster?=c
    Whichisnotawine?=b
    Whichisnotamountainrange?=a
    Inthemovie,"PaintYourWagon,"ClintEastwoodsang=a
    Thedrink"Screwdriver"contains=b
    RonaldReagan'sco-starin"BedtimeforBonzo"was=a
    Theslogan"Ittakestwohandstohandleawhopper"refersto=b
    Ifyouarrivedatapartywearingyourbirthdaysuit,youwould=d
    CesarChavezledaboycottof=a
    JamesBrownisoftenreferredtoas=d
    Wholostadaughterbutgaineda"meathead?"=c
    WhichU.S.SecretaryofStatewasborninGermany?=d
    WhowastheinventivegeniusbehindtheApplecomputer?=b
    "CloseEncountersoftheThirdKind"isabout=c
    IBMstandsfor=b
    WhowasNOTinthemovie"EasyRider?"=d
    LasVegasisfamousfor=c
    Theterm"WorkingGirl"refersto=b
    Makinga"HoleinOne"is=a
    Mybossis=d
    Howmanyprogrammersdoesittaketoscrewinalightbulb?=a
    Aharddiskis=a
    Insomepersonalads,TVstandsfor=b
    Lucy,Ricky,Fredand=d
    MelBrooksis=c
    Itiscustomarytotipabout=c
    Blackjackis=a
    Canadais=d
    OralRobertsis=b
    RichardNixonwas=a
    A747is=c
    Whips,chainsandhandcuffsare=a
    AMacintoshis=a
    Myparentsare=d
    Myfavoriteactoris=d
    Ihavehaironmy=d
    Whenit'snooninCaliforniainAugust,inSt.Louisit's=b
    Thebest"pick-up"lineis:=b
    The"Mile-HighClub"is=d
    Mysexlifeisbestdescribedas=c
    ElizabethTayloris=a
    JoanRiversis=c
    Whostarredin"BedtimeforBonzo?"=d
    Taxesshouldbe=a
    Amoonis=a
    MarlonBrandois=b
    Iampresently=d
    Herpesis=d
    ERAisanabbreviationfor=b
    G.GordonLiddywasassociatedwith=d
    WhatwasillegalduringProhibition?=b
    Bonnieand=b
    WhospendsthemosttimeinLasVegas?=b
    WhichU.S.Presidentwasnotelectedtooffice?=c
    Whichisnotacurrency?=c
    Whichisnotabaseballteam?=c
    Whomadearecordalbumwithacoverthatlookedlikeapairofbluejeans,completewithaworkingzipper?=a
    TheAmericantelevisiondebutofBobHope,DinahShore,Elvis,andtheBeatleswason=b
    MichaelDoonesburyfounded=b
    Thefirstbaseballplayertochallengethereserveclausewas=c
    ThefirstNegrotoplayMajorLeagueBaseballwas=a
    FormerCongressmanWilburMillswentforadipintheTidalBasinwith=b
    MarthaMitchellwas=c
    TheG-Spotissupposedtobe=b
    HughHefnerisusuallyphotographedin=d
    The1973album"DarkSideoftheMoon"wasrecordedby=a
    Whenplaying"Monopoly"you=b
    WhichisnotinHawaii?=c
    Whichisnotacar?=d
    PresidentEisenhower'snicknamewas=c
    BourbonStreetisin=d
    Doesapairofqueensbeatthreedeuces?=a
    CalvinKleinis=c
    Twobitsis=d
    CharlieMcCarthyand=d
    Whoisnotafamousmusician?=d
    Whichisnon-alcoholic?=c
    Whowasnotapolitician?=c
    ThelastnameofAnnette(ontheoriginalMickeyMouseClub)was=c
    "TiptoeThroughtheTulips"wasrecordedby=c
    Whichoneofthesewasnotawar?=c
    Who'sburiedinGrant'stomb?=d
    JohnF.Kennedydrovea=a
    PeterPiperpickedapeckofpickled=c
    AresultofWatergatewas=c
    Ifindcomputergameswithadultcontent=b
    TheAtlanticandPacificOceansareconnectedbythe=a
    Themostlikelyplacetofindvirginsis=c
    Whowrote"Tobe,ornottobe?"=a
    Thelargeststateis=b
    Utahisfullof=d
    TheleaderofNaziGermanywas=d
    LeeHarveyOswaldkilled=c
    Howmanymoleculesareinaglassofwater?=d
    IfaphysicianwerestrandedonadesertislandwithBoDerek,hewouldprobably=a
    IfBoDerekwerehere,I'daskherto=d
    JoeDiMaggioplayed=b
    ThemostpopulouscityintheUnitedStatesis=c
    Anehrujacketis=b
    SergeantPepperwas=c
    WhichisnotanAmericanarmedforce?=d
    Themosteffectiveformofbirthcontrolis=a
    WhichisnotacityinMexico?=c
    HerbAlpertandtheBrass=a
    "It'snotnicetofool"=b
    "Where'sthe"=c
    Whowasnotanastronaut?=a
    WhohasnotbeenaU.S.AttorneyGeneral?=b
    Whichisnotacheese?=d
    CaptainKangaroo'ssidekickwas=d
    MohammedAliis=c
    Whoisnotamassmurderer?=d
    Thereareaboutcaloriesinacanofbeer.=b
    JohnBelushiwason=d
    JamesEarlJoneswasthevoiceof=c
    Doonesbury's"UncleDuke"isbasedon=b
    InWestworld,"wherenothingcangowrong,"guestswereentertainedby=c
    Morkwasfromtheplanet=a
    Whowasbannedfrom"SaturdayNightLive"becausehelostatelephonepoll?=d
    Thephrase"Cuttingthecheese"refersto=d
]]]
 nothrottle = 10
script[cp]:
    code = [[[$(CRLF)
        last_question = "";
        color = ("$$(OPTION)" ? 3 : 15);

        func update()
        {
          if (!script_running(cpscript))
          {
            str = scraper_string("BAA64@@9c", "8x8", color, $$(COMPOSITE));
            if (str == "Pleaseanswera,b,c,ord:")
            {
              cpactive = true;

              text = scraper_string("QAAHs@@KPAAKP@@MzAAMz@@PXAAPX@@R7AAR7@@UfAAUf@@XDAAXD@@ZmAAZm@@
   cKAAcK@@euAAeu@@hSAAhS@@j2AAj2@@maAAma@@o9AAo9@@rhAArh@@uFAAuF@@wp", "8x8", 0, $$(COMPOSITE));

              question = substr(text, 0, strstr(text, "a."));
              answer = strmap(question, "$$(CPANSWERS)");

              if (question != last_question)
              {
                echo("Text: " + text);
                echo("Question: " + question);
                echo("Answer: " + answer);
                last_question = question;

                if (!prop("noautocp")) 
                  cpscript = script_run_async("cpauto", answer+"\r");

                if (!prop("notextcp"))
                  overlay_show("cpoverlay", 1, "The correct answer is: " + answer);
              }      
            }
          }
        }

        func cpauto(value)
        {
          input_lockout(true);
          sleep(1000);
          keyboard_type(value);
          sleep(500);
          input_lockout(false);
        }
    ]]]
end
