GEM_ANSWERS = [[[|
    =
    I'llbuildashiptocarrymeskyward.Ifitfalls,I'llnotbeharmed.ButIwillnevertellhowitisdone.WhatdoIhave?=Agate Turquoise Sapphire
    Imustrideuponafieryhorse,throughvalleysfilledwithaddersandseekthefatethatawaitsme.WhatshouldItakewithme?=Turquoise Sapphire Jet
    Insummer,myicedoesnotmelt.Theredeyebecomesclear.DemonsrunwhenIraisemyhand.WhatdoIhave?=Sapphire Lapis Jet
    Alas,sadnessclothesmelikealeadencloak.Awickedwomanliestome,butIfeardangerwillcomeuponmebysurprise.Whatwouldyougiveme?=Agate Turquoise Amber
    Ihaveafeverwhichhasdrivenmetomadness.MyteethloosenandItastebloodinmymouth.=Amber Agate Carnelian
    Iwouldcomfortafriendwhoisillandfearsthatdeathwillcomeuponhimwithoutwarning.Butifdeathshouldcome,letmygiftsguidehimbeyonddemon'sreachandtonewlife.WhatshouldIgivehim?=Carnelian Jet Opal
    Sadnessweighsuponmysoul.Myheartachestobefilled.WouldthatIcouldstealintomylove'schamberunseen.=Agate Carnelian Opal
    Ihavethreefears:Ifeartravellingbyship;Ifearmywifewillbeunfaithful:Ifeartheliesofmen.WhatshouldItakewithme?=Agate Lapis Sapphire
    IwillseekoutthedevilwhereheliesandIwillcrossmanyseastodoso.ThenIshallblasthimwithfirefromheaven.=Agate Lapis Jet
    Demonsdancetomycall.Iamathiefnonecancatch.Nosharpbladeworriesme.WhatdoIhave?=Carnelian Opal Jet
    Thedroughtlengthens,thecornwithersinmyfield,andawitchcursesmewithaglance.Whatwouldyougiveme?=Agate Lapis Jet
    Insummer,myicedoesnotmelt.Theredeyebecomesclear.DemonsrunwhenIraisemyhand.WhatdoIhave?=Sapphire Lapis Jet
    ApieceofskyfelltomyfeetandIpickeditup.Whereittouchedme,itraisedboils.Ifearitpoisonsme.Whatwouldyougiveme?=Lapis Sapphire Jet
    Mytreesareheavywithfruit,myheartisfullofalldesires,andmywifegivesbirthtoaholychild.WhatdoIhave?=Agate Carnelian Quartz
    Iliedying,cutdeeplybythesword,myfleshburns,spiritsofHadeshovertotakemysoul.Whatwouldyougiveme?=Carnelian Amber Jet
    Iamoldandmyhearingfailsme,Iamillandwonderwhendeathwillcomeforme,mymouthisdry.Whatwouldyougiveme?=Amber Opal Quartz
    ImustgointobattlewhereImaywellbewounded.ThenIwillknowgreatthirstandmyeyeswillburn.=Sapphire Lapis Quartz
]]]

GEMS = [[[|
    =
        Agate=151 92
        Amber=154 122
    Carnelian=186 105
          Jet=172 117
        Lapis=126 123
         Opal=137 133
       Quartz=180 130
     Sapphire=163 106
    Turquoise=143 109
]]]

COAT_OF_ARMS_FINGERPRINTS = [[[,
    fm3myOYNWBrlZxkqQid0d1To8W#NTkEDk72Tqsa#xj4ZWB7kIFHWNO=The Adegavion Kings
    @g6yOOWSF8zlh2htUid4MYHzMeSD7@rSL3GHMb3B1jJIAxD@B#LUZO=The Christian Britaines
    pamoyOwN2Djl5dSHwisXtq3Gr1zdv@#HDWy54BK1BjdH5In@@wh0JO=The Christian West Saxons
    JDhmKOn8DTvlxBAjQipDDzHzsf2W@yKh4oaLbs#tFjwajmr@7cuGpO=The Cornish Kings
    @g6yOOO3hD@loPMZMimy5#L@Car4TzUaJQWArN3bRjty05bzn4BOhO=The East Saxons
    hJ9LSOTj5oDluXhosibUtCTy5aHQv7qqdwGLaTidBj@O1Mj#T7SzlO=The Danish Kings
    XqmfWOiIsKjlZAVQwimIkrj#D1l9n9L7T4KAh9BptjJobqDyu@WCNO=The King of Man
    BQ6FqOoS0oTlJmGkYioIoGLHVXTMPLq3GIC57Vk8FjRU1@@LiDqF9O=The Kings of Ireland
    pamoyO@Sabzl5dSHwikQuOfGBAokfksEGKG5#c#Btj1lYz@kGeSWpO=The Later Saxon Monarks
    Ro1daODcTLbliX4nci3eFxPGHFo6b@7TYPm5uMqpljcbS0rKp2cBxO=The Mercian Kings
    cby5qOT5NgblgFkNwiSbKDTo2AgnLwJxbD#TGxBEtj6lcx3knhQiBO=The Norman Kings
    @g6yOOgrS@@l#3TS8iDvsmT@r3Spzx3Gt3KAMb3B1jcqe@Xz#yW29O=The South Saxons
]]]

charset[bow]:
    height = 9
    char[0x27]: bits = 100`600
    char[0x2c]: bits = 008`010
    char[0x2e]: bits = 010
    char[0x30]: bits = 3e0`450`490`510`610`3e0
    char[0x32]: bits = 230`450`490`510`210
    char[0x33]: bits = 220`490`490`490`490`360
    char[0x34]: bits = 0c0`340`440`440`7f0`040
    char[0x35]: bits = 720`510`510`510`4e0
    char[0x36]: bits = 3e0`490`490`490`460
    char[0x37]: bits = 400`430`4c0`500`600
    char[0x3a]: bits = 120
    char[0x3b]: bits = 010`120
    char[0x3f]: bits = 300`400`450`480`300
    char[0x41]: bits = 3f0`480`480`480`480`3f0
    char[0x42]: bits = 7f0`490`490`490`490`360
    char[0x44]: bits = 7f0`410`410`410`410`3e0
    char[0x48]: bits = 7f0`080`080`080`080`7f0
    char[0x49]: bits = 410`410`7f0`410`410
    char[0x4d]: bits = 7f0`200`100`0c0`100`200`7f0
    char[0x4e]: bits = 7f0`200`100`080`040`020`7f0
    char[0x4f]: bits = 3e0`410`410`410`410`3e0
    char[0x52]: bits = 7f0`480`480`480`480`370
    char[0x53]: bits = 320`490`490`490`490`260
    char[0x54]: bits = 400`400`400`7f0`400`400`400
    char[0x57]: bits = 7e0`010`010`060`010`010`7e0
    char[0x61]: bits = 020`150`150`150`0e0`010
    char[0x62]: bits = 7e0`110`110`110`0e0
    char[0x63]: bits = 0e0`110`110`110`0a0
    char[0x64]: bits = 0e0`110`110`110`7f0
    char[0x65]: bits = 0e0`150`150`150`0d0
    char[0x66]: bits = 080`3f0`480`480`400
    char[0x67]: bits = 0c0`128`128`128`1f0
    char[0x68]: bits = 7f0`100`100`100`0f0
    char[0x69]: bits = 5f0
    char[0x6b]: bits = 7f0`040`040`0a0`110
    char[0x6c]: bits = 7f0
    char[0x6d]: bits = 1f0`100`100`0f0`100`100`0f0
    char[0x6e]: bits = 1f0`080`100`100`0f0
    char[0x6f]: bits = 0e0`110`110`110`0e0
    char[0x70]: bits = 1f8`120`120`120`0c0
    char[0x72]: bits = 1f0`080`100`100`100
    char[0x73]: bits = 090`150`150`150`120
    char[0x74]: bits = 100`7e0`110`010
    char[0x75]: bits = 1e0`010`010`010`1e0`010
    char[0x76]: bits = 1c0`020`010`010`020`1c0
    char[0x77]: bits = 1e0`010`010`020`010`010`1e0
    char[0x79]: bits = 1c0`028`028`028`1f0
end

script[cp]:
    code = [[[$(CRLF)
        cpactive = "";

        func update()
        {
          if (!script_running(cpscript))
          {
            gemmatch = scraper_match("BAAZm@@wA", "zQTo#e4h48n91NSho8BrWXr1GPPobqCVYH2MAxwRd#C@6mPo5OwVFT", MF_MOUSE);
            druidmatch = scraper_match("BAAQp@@z2", "BtMNieZNLRmWAmp3w8DV9Sz196#JAkT3R@OMbdEgx#s3zpk9IaLP1T", MF_MOUSE);
            coatofarmsmatch = scraper_match("ByAIA8aXX", "$$(COAT_OF_ARMS_FINGERPRINTS)", MF_MOUSE);

            if (gemmatch)
            {
              question = scraper_string("GAAGF@@I9AAI9@@L2AAL2@@OuAAOu@@RmAARm@@UfAAUf@@XX", "bow", 0xFF);
              answer = strmap(question, "$$(GEM_ANSWERS)");
              echo(question);
              echo(answer);

              if (answer != "")
              {
                cpactive = answer;
                gems = [strword(0, answer),strword(1, answer),strword(2, answer)];

                if (!prop("noautocp"))
                  cpscript = script_run_async("cpgemauto", gems);

                if (!prop("notextcp"))
                  overlay_show("cpoverlay", -1, "!!" + gems[0] + ".png!! !!" + gems[1] + ".png!! !!" + gems[2] + ".png!!");
              }
            }

            if (druidmatch)
            {
              if (cpactive == "")
              {
                cpactive = druidmatch;

                duir = scraper_match("BBAR7@A@@", "8y7xuewM6u66ZZ64E8IM@IH1Qt8b9s3z7miMlyZUx##XOgT5rlRF9T", MF_MOUSE);

                if (!prop("notextcp") && duir)
                  overlay_show("meow", 1, "!!oakduir.png@400!!");

                if (!prop("notextcp"))
                  overlay_show("cpoverlay", -1, "!!druidcode.png@400!!");
              }
            }

            if (coatofarmsmatch)
            {
              echo(coatofarmsmatch);

              if (cpactive == "")
              {
                cpactive = coatofarmsmatch;

                if (!prop("notextcp"))
                  overlay_show("cpoverlay", -1, "!!coatofarm.png@200!!$(CRLF)The King of Man");
              }
            }

            if (!gemmatch && !druidmatch && !coatofarmsmatch && !duir)
            {
              cpactive = "";
              overlay_hide("cpoverlay");
            }
          }
        }

        func cpgemauto(gems)
        {
          mouse_force_relative_zero(true);
          input_lockout(true);
          sleep(2000);
          for (i = 0; i <=2; i++)
          {
            coords = strmap(gems[i], "$$(GEMS)");
            x = strword(0, coords);
            y = strword(1, coords);
            mouse_move_abs(2*x, y); sleep(500);
            mouse_click(0); sleep(1500);
            keyboard_type("\r"); sleep(500);
          }
          sleep(500);
          input_lockout(false);
          mouse_force_relative_zero(false);
        }
    ]]]
end
