FINGERPRINTS = [[[,
    @VCyif7Bwfn15W4bg9s5LsD0YJlwf54fDg6NkUzLF@G3Anb4iC31lS=Celie
    X9TwSfyw@dX1ZxzQs9i8Uo70AmqRf4MYXEmMVIAi9#P648z4PoispS=Celie
    L#q5OZdG@sf1y#7R87i5Uxry0LY@35kROsqLLwMX55tyrcj#W1aDdU=Celie
    d0RgeZLy5Oz1LahOM7NLn6by9PlOX#yq6CCMcY3YJ#3PLC3#ildLxU=Celie
    WIWmifmWW0j15ENRo9rLXJ@0roqLv54haR6NIpHVR@AQ7eD5qDOnhS=Clarence Sparrow
    E4Ud2fzPEuz1myJTY9#HmJv0zQvYz5SNrPWNOJvL5@sViU74ml87RS=Clarence Sparrow
    6EU#WZB4#ST124HDM7J8gh@yL3sxX56RruyL0pp355QhXID5hGA@9U=Clarence Sparrow
    EYz66Z77dX@1aGCgs7nFHbHymbp0z5b5LiWLz2GEl5gZ3tT##IqhJU=Clarence Sparrow
    m@njefATL9f0XPwmA9dv2#305v8Yn5IplEGNFrl4t@k13hD5b6mjFS=Col. Dijon
    ycuLifl4ykP19nQNA9UCrAb15#D9j5pTh1mNSlXA5@2Kpob4BJj7BS=Col. Dijon
    @hrt2ZH@0F7yRkkrI7b@GZXyTtH2v5337ziLAUhdV5u8#D75D06tBU=Col. Dijon
    XZfjeZSGxRX1IOZFQ721aq71KX6Sn5Dw7UqLneKJt5iieLP#Yual9U=Col. Dijon
    tunA2faT5cj1eHaGE9fA#kP0@hhmP53DiT#NeDWhd#2E6Ej54LK2dS=Dr. Feels
    pik6CfdVo4L0R1ix09LYK6v0mMjPf4MTi1mNHIbkJ@Wv#wv5FUU0pS=Dr. Feels
    NSF42ZBsB3X1yEN8o7NZCH3y#GsBH5ZjLeuLvskvR#QU2uH5ih#ZtU=Dr. Feels
    @I6@eZaIeo@ybADDs7nCdJHyQj4Zj#iOdDqL5awGN5JDPx75gGJSFU=Dr. Feels
    WspeqfGSUVD1IUZt09itHLL0FwAJP4zmOQuNW#TMt@dyUCf4QdAM5S=Ethel Prune
    viKvifCroMT1I9mFY9KsF6z0iv0HT5PgHmmNqPRyp@dEzDL4R3S@tS=Ethel Prune
    wrj1yZFZzNv1Y@j647#4lF7ywjYZ75S0eFCLR80S157e6cz#B5kW5U=Ethel Prune
    WN8sOZD9j671tyHdQ7EiIYjy5jBjL#k1IO2LleZlR5g8pvT#uUichU=Ethel Prune
    2NwPOf5zI730BKUNg96Lpzv1fP@4v5jy8MmNqjmZt@S#Xdf4#Eg#1S=Fifi
    DTSLCfvobZL1yoveI9oUMUv1qOH0f4DUiNiN7ePLh#7U8zX5D3AAZS=Fifi
    KlgQSZViaQDyxz4w87Pcqsb1In6Aj5uDYnqLBqiu151Ul9H#dmu@9U=Fifi
    v0A76Z7FmFX1CIzW87K72171kmTdP#p12fCLU9JKV#489G35sJfShU=Fifi
    JoScKfEGupf0MkHuM9A89aj1Ip4DX4S3LKWNUxWFN@Ak6@35GPzJtS=Gertrude Dijon
    lfudufoPENf1cAGtc9d0ybX18U94z4BN#1ON#VAJN@B#jEX4hh7XxS=Gertrude Dijon
    Ggdb2ZmjdX3yegzFE7ZEP2D1HaV9r#1umc#LfNDMN5GMTVj5pR6SRU=Gertrude Dijon
    E@HBOZgDD871wA1aQ7COpQb15ga5b#OW#HSLKt3c55eqXWv#T8SuZU=Gertrude Dijon
    0eDoGfy@2Qv0nJZVg9MHdz@1ndBJD46YsTWMV5uz1@tB8GD4Zax2FS=Gloria Swansong
    HTXOaf@Y1hv1NO8Wc9fySdv0nOsKr4uU6nGN0MbxZ@lPjGz4hsbjVS=Gloria Swansong
    FolSuZ@vM3P1uw0I07b2X9by@D8TT#UXGK6LQPKt15UIRpT#cbmNZU=Gloria Swansong
    3CmpqZTtyYbyi@Efo7NdT@z1biVvz#K20k#MDfvAx50Ycdr#XGvBZU=Gloria Swansong
    v94tifo5PlD0eY9E09Nbt5D0GExUz4lz@X#NzX4IR@QTLwj5s32p5S=Jeeves
    TlojyfTONy@0RC2os92IgHL1W9OFz4tYnVKMIL0Ih@2dgbb5UB9qVS=Jeeves
    Qt2SOZ2wKWfyi8YIk71s3oTy30@pn#pt@HOLdQYqV5KSSuv5r57NxU=Jeeves
    hLprKZXOGULybeDV07#vS6P1K3ssH#5FqzWMk6xAx5AtSgP5xRYghU=Jeeves
    GgvmyfeZLr@15CaMA9RMzxH0TL1#r53KMtmN4pkFZ@MpzKv5naVRVS=Laura Bow
    5xzPSfcA59D1pWz@A9ZsUNn0dfUUz4hmJ2KM@Ce4h@rKpy74TYMSNS=Laura Bow
    HNxQaZaBjyb1A1#wQ7rY#9Hy@yFs@5ohIW6LeEibh5lj9bT5zgw3VU=Laura Bow
    PEmIOZqM9iz1KL2xc7kxu0jyzlgRr#712keM8lBMF5zIwlX#ps0hNU=Laura Bow
    mQhhefOUdTr0DZO8o9zy9Nf0zW5Fz40pzPiNmorER@5Eo4@4BmQIdS=Lillian Prune
    G#ff6f7Cjvz0CR@349lETdv0utOjP4BAX3eNeeFap#hWUFr5iLQ#VS=Lillian Prune
    DPhu6ZcDphzysTECk7SL4kPyauZt7#Mub8GLrkD5V#874W35iW4lZU=Lillian Prune
    siEvqZbaP3ny5tZ@Y7Kt@ZzyuUlPH#rPnnGLDXA7N5ZFrq7#TPV29U=Lillian Prune
    4spyGfVWvI71BXKsU9LzZvv1UEb3L4gLmeaNdrBwV@@@oXv472NodS=Rudy Dijon
    GD5@affAtj31cAGtc94REWj0MypDj58m8aGNK7bH1@bDQcr4lbU3dS=Rudy Dijon
    aaoLiZziJ5f1OXXtE7t3px@1GKPTX#mADx#LnVq6V5M8IAP#7JNOlU=Rudy Dijon
    I@DUmZAyc2j1wA1aQ7DaP#DyncKn35#urFaLRWXOd57X#6@#GjBqJU=Rudy Dijon
]]]

MOUSECOORDS = [[[|
    =
    Celie=15 55
    Clarence Sparrow=275 150
    Col. Dijon=275 80
    Dr. Feels=20 135
    Ethel Prune=255 185
    Fifi=15 110
    Gertrude Dijon=25 155
    Gloria Swansong=275 110
    Jeeves=270 54
    Laura Bow=165 185
    Lillian Prune=65 185
    Rudy Dijon=25 80
]]]

script[mouse]:
    condition = is_game() || is_demo()
    code = mouse_force_relative_zero(true)
end

script[cp]:
    code = [[[$(CRLF)
        cpactive = "";
        answer = "";
        coords = "";
        func update()
        {
          if (!script_running(cpscript))
          {
            answer = scraper_match("BcAZmkzns", "$$(FINGERPRINTS)");

            if (answer != "")
            {
              echo("Answer: " + answer);
              coords = strmap(answer, "$$(MOUSECOORDS)");

              if (coords != "")
              {
                cpactive = true;
              
                if (!prop("notextcp"))
                  overlay_show("cpoverlay", -1, "The fingerprint belongs to " + answer);

                if (!prop("noautocp"))
                  cpscript = script_run_async("cpauto", (strmap(answer, "$$(MOUSECOORDS)")));
              }
            }
            else
            {
              cpactive = false;
              overlay_hide("cpoverlay");
            }
          }
        }

        func cpauto(coords)
        {
          input_lockout(true);
          sleep(2000);
          x = substr(coords, 0, strstr(coords, " "));
          y = substr(coords, strstr(coords, " ")+1, 10);
          echo("Moving mouse to: " + x + "," + y);
          mouse_move_abs(x, y); mouse_click(0);          
          sleep(500);
          input_lockout(false);
        }
    ]]]
end