FINGERPRINTS = [[[,
    2XQduRLUKBXyGfQm4zR95Az7e#M9v9Rr1E#DrIE2dyBtEIz1LSSelf=2737
    ssMwKdDpUNL0PnsBY@bn#5f2QwBkH7LEfTyPDxOvZ8tXNyz7M2eClR=2737 // CGA
    Xi9rWfPLwvn0zzjRA9eAGAj0OyA7r5D7vz2Nfd9id@Jih6H5MW3PRT=2737 // Composite
    Wmo0GRc6e9LzDURn0zK9rMb6FGJfH9X@teKD2h07xyQvQG71CfvTtf=2867
    7QIOSdKDQAX20iOj4@GoqnX22pjob71TF02PgXB#J8xKCpP7Mc8ItR=2867 // CGA
    ugNLWfIj8j@0Iq0Lo9PTTvP0CmdtD5o71rSND0F2J@4W#kv5PWdvNT=2867 // Composite
    tMB@CRJVnqb1EcEDozBlVaf1FGsQv982onWDkFfKJyjXWFz1v5qGZf=2868
    h2sXudcNRzX1dp4lw@FB@K31AkYvX7k4fWOP07mEN8Bhymb7ZQJBFR=2868 // CGA
    laR4mfYwgmL1vY3Zk9GaDaH15hmEj5YUENCNMzPvd@DjwZH5aGAlZT=2868 // Composite
    Wmo0GRHJh5@zDURn0zK9rMb6zt5wr9X@teKDl3TYxyWvOcr1xkAU9f=3425
    7QIOSdJtSHD20iOj4@GoqnX2yGBBT71TF02PZ17cl8zqkK37PY9RRR=3425 // CGA
    ugNLWfK40av0Iq0Lo9PTTvP0L#f#H5o71rSN59u7h@@Dlj75JMRdNT=3425 // Composite
    tMB@CRIM3XD1EcEDozt#4Bf1YyncT9F5dW#Dxx8wFyCAo1v1dRWZtf=3642
    h2sXudPiJb31dp4lw@vhcJD1bhA8b7@80ZiPuDWZN8ceZm@72CLNdR=3642 // CGA
    D#ya#RO#5A7#SuyuczjCbgP6Pnmtv1ww6LKDK38t1yXoPmD18#2rhf=3787
    nqNGadR4HlX18ihR0@zTsLv21nlyD7foXa#P86Fsp88uFKX7v98mxR=3787 // CGA
    kYwq2f4V0Cj1yw02099DKPb0#FCS35jx#1KNkstiJ@W@5aP5YhcO5T=3787 // Composite
    D#ya#RO#5A7#Suyucz@hR0L6NP2#b1ww6LKDjr51p5UAM3j1RryD5U=3825
    nqNGadQTAEX1hlAlc@L4ty@2gVxzv7LrxR#MxooPl8u#azT7z9KBZR=3825 // CGA
    nqNGadR4HlX18ihR0@L4ty@22LChb7foXa#PxooPl8HToyn7Gx4HpS=3825 // Composite
    2XQduRD6HEfyGfQm4zF42I37oqUgb99Wt9CDndk41yUV3Lz1C6qrxf=5464
    ssMwKdWmrtL0PnsBY@I9JY326TLj771JNRiPqwzeZ8nZMCH79r765R=5464 // CGA
                                                                // Composite missing
    tMB@CRuLW7b1EcEDozFU3s31ci8X79F5dW#DkFfKJyD3Rij1v5qGZf=5633
    h2sXudPiJb31dp4lw@vhcJD1vlGML7@80ZiP07mEN8BB7gn7ZQJBFR=5633 // CGA
                                                                // Composite missing
    Wmo0GR1amRjzDURn0zLBoQf6zuZ7v17vjaeDiDphF5rwLNr1MG8E9U=5834
    7QIOSd2mpon20iOj4@wYxgP2dM7vb7TGAmOPhwhGZ8SI2ej7cT3JFS=5834 // CGA
                                                                // Composite missing
    2XQduRbDrkDyGfQm4zR95Az7nAC2P9Rr1E#DlGVNZ5VCVSH12hU7NU=5968
    ssMwKd6CIqP0PnsBY@bn#5f2dZhLH7LEfTyPRwj7t8T4K0@78Nf#ZS=5968 // CGA
    Xi9rWfjGDor0zzjRA9eAGAj0#ECuz5D7vz2NTR8VN@yPcYv5XvB8ZS=5968 // Composite
    Wmo0GRYD#yrzDURn0zm4cCj6L#rpz9BAYPuDiDphF5rwLNr1MG8E9U=6262
    7QIOSdPN1Pj20iOj4@FLigv2bHvVT7bkAmiPhwhGZ8SI2ej7cT3JFS=6262 // CGA
                                                                // Composite missing
    D#ya#R9Omdv#Suyucz@hR0L6PiF2b1ww6LKDBHZiRynrCPL1ggeopf=7448
    nqNGadzfrVH18ihR0@L4ty@2tRdgD7foXa#P5h26N8kIxqv7kxvipR=7448 // CGA
    kYwq2fe0@1n1yw0209NndWX068Ipj5jx#1KN0Twz9@MUZrD5ugIeVT=7448 // Composite
    2XQduRD6HEfyGfQm4zR95Az7uhShf9Rr1E#DlGVNZ5LFqtr12hU7NU=8487
    ssMwKdWmrtL0PnsBY@bn#5f2qLjqb7LEfTyPRwj7t8DqyZL78Nf#ZS=8487 // CGA
    Xi9rWf70SZ70zzjRA9eAGAj0PLtD@5D7vz2NTR8VN@w6xbb5XvB8ZS=8487 // Composite
    D#ya#RO#5A7#SuyuczLoUNn6W8MRX9ww6LKDBHZiRyKWO9P1ggeopf=8627
    nqNGadR4HlX18ihR0@zTsLv2D9RW37foXa#P5h26N8qAc3P7kxvipR=8627 // CGA
                                                                // Composite missing
]]]

script[cp]:
    code = [[[$(CRLF)
        cpactive = "";
        answer = "";

        func update()
        {
          if (!script_running(cpscript))
          {
            answer = scraper_match("BYNUzlznX", "$$(FINGERPRINTS)");

            if (answer != "")
            {
              echo("Answer: " + answer);

              if (!prop("noautocp"))
                cpscript = script_run_async("cpauto", answer+"\r");

              if (!prop("notextcp"))
                overlay_show("cpoverlay", 1, "This lovely lady’s number is 555-" + answer);
            }
            else
            {
              cpactive = false;
              overlay_hide("cpoverlay");
            }
          }
        }

        func cpauto(value)
        {
          input_lockout(true);
          sleep(1000);
          keyboard_type(value);
          sleep(500);
          input_lockout(false);
        }
    ]]]
end