CPANSWERS = [[[|
    =
    WhichEgyptiangodwastheGreatCacklerwholaidtheCosmicEgg?=Amon Ra
    WhichEgyptiangodinventedmummification?=Anubis
    WhowastheEgyptiangoddessoflove?=Hathor
    WhichEgyptiangoddesswasthemistressofmerriment?=Hathor
    WhichEgyptiangoddesswasoneoftheoldestknowngoddessesofEgypt?=Hathor
    WhichEgyptiangodwasthespiritoflight?=Horus
    WhowasthemostpopularEgyptiangoddess?=Isis
    WhichEgyptiangoddesswasconsideredthe"Queenofallgods"?=Isis
    WhowastheEgyptiangodoffertility?=Min
    WhichEgyptiangodwasthebringerofrain?=Min
    WhowastheEgyptiangodofroadsandtravelers?=Min
    WhichEgyptiangoddessrepresenteddarkness,decay,anddeath?=Nephthys
    WhichEgyptiangodmadecropsgrow?=Osiris
    WhichEgyptiangodbuiltthecities?=Ptah
    WhichEgyptiangodprotectedartists?=Ptah
    WhichEgyptiangodwasthepatronofcraftsmen?=Ptah
    WhichEgyptiangodsymbolizedevil?=Seth
    WhichEgyptiangodrepresenteddarkness?=Seth
    WhichEgyptiangodwastheLordofUpperEgypt?=Seth
    WhichEgyptiangodwasworshippedinCrocodilopolis?=Sobek
    WhichEgyptiangodwasworshippedincitiesthatdependedonwater?=Sobek
    WhowastheEgyptiangodofwisdom?=Thoth
    WhichEgyptiangodcreatedhieroglyphics?=Thoth
    WhichEgyptiangodwrotethe"BookoftheDead"?=Thoth
    WhichEgyptiangodwasthepatronoftheartsandsciences?=Thoth
]]]

MOUSECOORDS = [[[|
    =
    0=80 90
    1=180 90
    2=280 90
    3=380 90
    4=480 90
    5=580 90
    6=80 150
    7=180 150
    8=280 150
    9=380 150
    10=480 150
    11=580 150
]]]

GODS = [[[|
    =
     Amon Ra=WxT4pZLq3#U0BGYtXxr5u7qpU8#lA#qc68QfvGVrhjnAcCs#JQ19eU=,NJqFKZzz69H5h87swwzRcCT1cwxMn1wizEaKjeZat6AZsar19Bix9f=
      Anubis=7raylfsLZY44WSre3vEd#xEynnB36Qo0WU9ZMfGAC5E41a8#p@gnWU=,oIAjuaEEgBn5VrMMgwLIFDLyuampT9PFmUSAefDD15gsCor1bc8L9f=
      Hathor=#tVCZfkWMJkVL#hOXvXVF0c0#bE3epfG5TtBuNNkarCtLQGojMrQqG=,2UYWmaVVYTL5zRx8kwyugOLxOxjf3x#fXPmAIlwrl5hPv8Px2sMWJf=
       Horus=D2Ey#Dhan1tmM0EjKP3E09AyDZnm#i9iEc9egys8ar9sVj5NldWhCU=,m0YbuaJxsGbzcayBIwAqJuHyx1m6P@yuic2A09MeB5DKE5r1DrwUlf=
        Isis=tZMlhfBhRMmAdzVW@vwyVEI0#E5kePuIApNNfL8m3KBBisaapwi46S=,wm3viaqwSIzxppw0kwAE037xHwyGv9eFwsKA0cRn15AGONL@Xas89f=
         Min=uVAr#Dz1fmFYQa5DFnoJ5Z3o#GWhqHkV10hBTRJ0fTorEu2lszszKU=,SWOyaaFtO7L5tA#cE6HoxDrxwOSoz9JQLLyAhQrFZ6SaL93@SGhnxf=
    Nephthys=puoreDWTyZ9YWu5#chWCRP5zP@10SXPScXsf7DfqKr5ItKGSC9JTWU=,2fs0Ga#JxSH5bZo8AwhHpNX9lw6kP9CrfbuK2P@V55N@Ak3x4XcmZf=
      Osiris=L4AS9ZrEFXOcs3ECD7s4@HgyB9Kd4ytMEZtBmsl6u@v9fpgsp7#FWU=,Qt02KZKS#BrxVSKYQwQYdxjyI6cG310RDXiApI9xl6ARrUT1N7Y19f=
        Ptah=UPtu7IPHvDbo#Rp73xgnA15ByfUzp5hvGUnshmyqxjJ4NiY#q92jCU=,6bWp2eFBCHn5KamnQwxTy5by@QPqv9exHr#EKdvIl6Av5#P1MXsjVf=
        Seth=lJFoFTka5JCuwSFdJoNDihaclKJB6i8Z80r3eLvgG545b484ESmjWG=,bXFt#SOjsOHzbLEXQ4nFPzP96CCvf@zqE3KI7exVN5tqwjX16MZ@pf=
       Sobek=nt6hVfBQa2GcZzhdDvbRLbUg6xM0OdGOcmFL6Uq2K5xb@mTkln3PuH=,otpMqaaiD2PxjGHakweMAQzyILAC@xhi@9aAH5ae55dYkKP1oWrZBf=
       Thoth=P9BEhf4UUt2R3bNgHva5uzU06LdDbkU7MUZZvZG5DKN5A86l8ZA9aG=,Kxyg#a90MWr9drmDkww9tN3x#N2nv1k61BOAguX8V5dCUqj@tILqpf=
]]]

HINTS = [[[|
    =
     Amon Ra=!!amonra.png@400!!
      Anubis=!!anubis.png@400!!
      Hathor=!!hathor.png@400!!
       Horus=!!horus@400!!
        Isis=!!isis.png@400!!
         Min=!!min.png@400!!
    Nephthys=!!nephthys.png@400!!
      Osiris=!!osiris.png@400!!
        Ptah=!!ptah.png@400!!
        Seth=!!seth.png@400!!
       Sobek=!!sobek.png@400!!
       Thoth=!!thoth.png@400!!
]]]

charset[vga]:
    height = 9
    char["]: bits = 600`000`600
    char[?]: bits = 200`400`4a0`500`200
    char[B]: bits = 420`7e0`4a0`4a0`5a0`240
    char[C]: bits = 3c0`420`420`420`440`280
    char[D]: bits = 420`7e0`420`420`440`480`300
    char[E]: bits = 520`7e0`520`520`/Users/monochromatic/Library/Application Support/Aaron Giles/DREAMM/dreammpacks/sierra-dreamm-main/dreamms/cp-lb2.inc420`420`240
    char[G]: bits = 3c0`420`420`420`4a0`2c0`080
    char[L]: bits = 420`7e0`420`020`020`040
    char[Q]: bits = 3c0`420`420`420`440`4a0`320
    char[U]: bits = 400`7c0`420`020`020`040`480`700`400
    char[W]: bits = 400`7e0`420`040`480`7e0`420`040`480`700`400
    char[a]: bits = 040`2a0`2a0`2c0`1e0`020
    char[b]: bits = 420`3e0`120`120`140`080
    char[c]: bits = 1c0`220`220`140
    char[d]: bits = 0c0`120`120`540`7c0`020
    char[e]: bits = 1c0`2a0`2a0`2a0`120`040
    char[f]: bits = 120`3e0`520`400
    char[g]: bits = 190`250`250`3a0`3c0
    char[h]: bits = 420`7e0`040`080`120`1e0`020
    char[i]: bits = 120`5e0`020
    char[k]: bits = 420`7e0`100`280`260
    char[l]: bits = 420`7e0`020
    char[m]: bits = 220`1e0`0a0`100`220`1e0`0a0`100`220`1e0`020
    char[n]: bits = 220`1e0`0a0`100`220`1e0`020
    char[o]: bits = 1c0`220`220`240`180
    char[p]: bits = 410`3f0`150`240`280`300
    char[r]: bits = 220`3e0`120`200`200
    char[s]: bits = 120`2a0`2a0`2a0`240
    char[t]: bits = 100`7c0`120
    char[u]: bits = 200`3e0`020`040`280`3e0`020
    char[v]: bits = 220`3e0`020`040`280`300`200
    char[w]: bits = 200`3e0`040`280`3e0`040`280`300
    char[y]: bits = 200`380`050`050`290`3e0
    char[z]: bits = 320`260`2a0`320`260
end

charset[ega]:
    height = 7
    char["]: bits = c0`00`00`00`c0
    char[,]: bits = 02`00`0c
    char[?]: bits = 40`00`80`00`94`00`a0`00`40
    char[B]: bits = 84`00`fc`00`94`00`94`00`b4`00`48
    char[C]: bits = 78`00`84`00`84`00`84`00`88`00`50
    char[D]: bits = 84`00`fc`00`84`00`84`00`88`00`90`00`60
    char[E]: bits = a4`00`fc`00`a4`00`a4`00`84`00`84`00`48
    char[G]: bits = 78`00`84`00`84`00`84`00`94`00`58`00`10
    char[L]: bits = 84`00`fc`00`84`00`04`00`04`00`08
    char[Q]: bits = 78`00`84`00`84`00`84`00`88`00`94`00`64
    char[U]: bits = 80`00`f8`00`84`00`04`00`04`00`08`00`90`00`e0`00`80
    char[W]: bits = 80`00`fc`00`84`00`08`00`90`00`fc`00`84`00`08`00`90`00`e0`00`80
    char[a]: bits = 08`00`54`00`54`00`58`00`3c`00`04
    char[b]: bits = 84`00`7c`00`24`00`24`00`28`00`10
    char[c]: bits = 38`00`44`00`44`00`28
    char[d]: bits = 18`00`24`00`24`00`a8`00`f8`00`04
    char[e]: bits = 38`00`54`00`54`00`54`00`24`00`08
    char[f]: bits = 24`00`7c`00`a4`00`80
    char[g]: bits = 32`00`4a`00`4a`00`74`00`78
    char[h]: bits = 84`00`fc`00`08`00`10`00`24`00`3c`00`04
    char[i]: bits = 24`00`bc`00`04
    char[k]: bits = 84`00`fc`00`20`00`50`00`4c
    char[l]: bits = 84`00`fc`00`04
    char[m]: bits = 44`00`3c`00`14`00`20`00`44`00`3c`00`14`00`20`00`44`00`3c`00`04
    char[n]: bits = 44`00`3c`00`14`00`20`00`44`00`3c`00`04
    char[o]: bits = 38`00`44`00`44`00`48`00`30
    char[p]: bits = 82`00`7e`00`2a`00`48`00`50`00`60
    char[r]: bits = 44`00`7c`00`24`00`40`00`40
    char[s]: bits = 24`00`54`00`54`00`54`00`48
    char[t]: bits = 20`00`f8`00`24
    char[u]: bits = 40`00`7c`00`04`00`08`00`50`00`7c`00`04
    char[v]: bits = 44`00`7c`00`04`00`08`00`50`00`60`00`40
    char[w]: bits = 40`00`7c`00`08`00`50`00`7c`00`08`00`50`00`60 // 
    char[w]: bits = 40`00`7c`00`08`00`50`00`7c`00`08`00`50`02`62 // Yeah
    char[w]: bits = 40`00`7c`00`08`00`50`00`7c`00`08`02`52`00`60 // 
    char[y]: bits = 40`00`70`00`0a`00`0a`00`52`00`7c
    char[z]: bits = 64`00`4c`00`54`00`64`00`4c
end

script[mouse]:
    condition = is_game() || is_demo()
    code = mouse_force_relative_zero(true)
end

script[cp]:
    code = [[[$(CRLF)
        cpactive = "";
        question = "";
        regions = ["BDaR7Mzma", "BNAR7Wama", "BWmR7gAma", "BgNR7pmma", "BpzR7zNma", "BzaR78zma", "BDamuMz7N", "BNAmuWa7N", "BWmmugA7N", "BgNmupm7N", "BpzmuzN7N", "Bzamu8z7N"];

        func update()
        {
          if (!script_running(cpscript))
          {
            if ("$$(VIDEO_DRIVER)" == "EGA640.DRV") question = scraper_string("CAAIU@@KkAALN@@Nc", "ega", 0xF);
            else question = scraper_string("CAAIA@@K4AAK4@@Nx", "vga", 0x17);

            answer = strmap(question, "$$(CPANSWERS)");
            god = strmap(answer, "$$(GODS)");

            if (answer != "")
            {
              echo(god);

              for (region = 0; region < 12; region++)
              {
                echo(regions[region]);

                match = scraper_match(regions[region], god, MF_MOUSE);
                if (match)
                {
                  regionmatch = region;
                  break;
                }
              }

              echo("Question: " + question);
              echo("Answer: " + answer);
              echo("Region match: " + regionmatch);

              coords = strmap(regionmatch, "$$(MOUSECOORDS)");

              if (coords != "" && answer != "")
              {
                if (!prop("noautocp"))
                  cpscript = script_run_async("cpauto", coords);

                if (!prop("notextcp"))
                  overlay_show("cpoverlay", -1, strmap(answer, "$$(HINTS)"));
              }
              
            }
            else
            {
              overlay_hide("cpoverlay");
            }
          }
        }

        func cpauto(coords)
        {
          input_lockout(true);
          sleep(2000);
          echo("Moving mouse to X: " + strword(0, coords) + "   Y: " + strword(1, coords));
          mouse_move_abs(strword(0, coords), strword(1, coords));
          sleep(1000);
          mouse_click(0);
          sleep(500);
          input_lockout(false);
        }
    ]]]
end
